### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by romanown** [mderrick/react-html5video#131]
when I go to the page with the video from the main page of the site it works well. but when I go to the page with the video on a direct link then such an error.
ReferenceError: navigator is not defined
    at /var/www/dfor.ru/node_modules/react-html5video/dist/index.js:2496:61
    at Video.render (/var/www/dfor.ru/node_modules/react-html5video/dist/index.js:259:35)

**Comment by gazreese** [comment]
I get the same thing

**Comment by mderrick** [comment]
Sounds like you're both server side rendering. This library can't be server side rendered. You should check and render a placeholder when rendering on the server.

**Comment by romanown** [comment]
Thank You for Youre answer. Can You changing this component for control this problem?

> -- 
Roman

**Comment by Brightchild** [comment]
Is there a solution to this problem? Hope reply

**Comment by jonanderdev** [comment]
@Brightchild @romanown 
We encountered the same problem.
Is a typical issue with server side rendering and some libs that make use of things like navigator or window. So I implemented a simple fix and submitted a PR with it.
Hope it helps you guys as well as it helped me.

**Comment by romanown** [comment]
thank you. I deleted this line and it works for me.

**Comment by twotabsofacid** [comment]
Anyone else finding themselves here: since there PR was never merged a different workaround I found was to use the [react-no-ssr](https://www.npmjs.com/package/react-no-ssr) package and wrap the `<video>` tags within a `<NoSSR>` tag. Ugly but it stopped stuff from breaking.

Hope this helps someone.
